apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
jobs:
  job1:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      approvers: 9157afb6-9594-11ee-9328-42010a83ae92,84318240-2a5c-11f0-8b52-42010a83ae54
